package com.darlyncr.animals;

enum BreedsDogs {
 BULLDOG(), CHIHUAHUA, PINCHER, DOBERMAN, PASTOR, PUG

}

enum BreedsHorses {
 PURA_SANGRE, CUARTO_DE_MILLA, ARABE, APPALOOSA, PERCHERON, PINTO

}

enum BreedsCats {
 PERCIA, SIAMES, ANGORA, BENGALA, BIRMANO, BOSQUE_NORUEGO

}

